name: Install Qt with YAQTI

on:
  pull_request:
    branches:
      - main # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: WillBrennan/yaqti
        with:
          version: '6.2.0'
          host: 'linux'
          target: 'desktop'
          modules: 'qtcharts qtwebengine'
